import type {ReportFinding, AgentReport} from '../agents/types';
const escape = (value:string) => value.replace(/[&<>"']/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
function safeUrl(value:string) {
  try {const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?escape(url.href):null;}catch{return null;}
}
const paragraphs=(value:string)=>value.split(/\n\s*\n/).filter(Boolean).map(p=>`<p style="margin:0 0 14px;line-height:1.7;">${escape(p).replace(/\n/g,'<br>')}</p>`).join('');
const heading=(text:string)=>`<h2 style="margin:0 0 18px;color:#203e35;font-size:21px;line-height:1.3;">${text}</h2>`;
const section=(content:string)=>`<tr><td class="pad" style="padding:28px 32px;border-top:1px solid #e5e5da;">${content}</td></tr>`;
export function reportEmailTemplate(report:AgentReport):{html:string;text:string} {
  const status=(finding:ReportFinding)=>finding.kind==='simulation_hypothesis'?'Simulated perspective':finding.verification?.status==='supported'?'Supported by cited source':finding.verification?.status==='contradicted'?'Conflicts with cited source':'Insufficient evidence';
  const referencedSources=(finding:ReportFinding)=>report.sources.filter(source=>finding.sourceIds.includes(source.id));
  const conversations=(finding:ReportFinding)=>finding.conversationIds.map(id=>report.conversationReferences?.find(reference=>reference.id===id)?.label??'Agent discussion');
  const comparisonNames=(finding:ReportFinding)=>(finding.comparisonAgentIds??[]).map(id=>report.comparison?.results.find(result=>result.agentId===id)?.name??'Resident assessment');
  const sourceLink=(source:AgentReport['sources'][number])=>{const url=safeUrl(source.url);return url?`<a href="${url}" style="color:#205f4a;text-decoration:underline;">${escape(source.title)}</a>`:escape(source.title);};
  const quotes=(finding:ReportFinding)=>(finding.evidence??[]).filter(item=>referencedSources(finding).some(source=>source.id===item.sourceId&&item.quote.trim()&&source.excerpt.includes(item.quote)));
  const findings=report.findings.map((finding,index)=>`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 18px;border:1px solid #dedfd5;background:#fafaf5;"><tr><td style="padding:20px;"><p style="margin:0 0 10px;font-family:monospace;font-size:11px;letter-spacing:1px;color:#526457;">${String(index+1).padStart(2,'0')} / ${status(finding).toUpperCase()}</p><h3 style="margin:0 0 10px;color:#203e35;font-size:17px;line-height:1.4;">${escape(finding.title)}</h3>${paragraphs(finding.detail)}${finding.verification?`<p style="font-size:13px;line-height:1.6;color:#667066;">${escape(finding.verification.reason)}</p>`:''}${quotes(finding).map(item=>`<blockquote style="margin:14px 0;padding:10px 14px;border-left:3px solid #a8ba84;line-height:1.6;">${escape(item.quote)}<br>${sourceLink(report.sources.find(source=>source.id===item.sourceId)!)}</blockquote>`).join('')}<p style="margin:12px 0 0;color:#667066;font-size:12px;line-height:1.6;">Sources: ${referencedSources(finding).map(sourceLink).join(', ')||'No source cited'}<br>Conversations: ${escape(conversations(finding).join(', ')||'None')}${comparisonNames(finding).length?`<br>Comparison perspectives: ${escape(comparisonNames(finding).join(', '))}`:''}</p></td></tr></table>`).join('');
  const list=(items:string[],ordered=false)=>`<${ordered?'ol':'ul'} style="margin:0;padding-left:22px;">${items.map(item=>`<li style="padding:0 0 12px;line-height:1.7;">${escape(item)}</li>`).join('')}</${ordered?'ol':'ul'}>`;
  const sources=report.sources.map(source=>`<p style="margin:0 0 16px;line-height:1.6;">${sourceLink(source)}</p>`).join('');
  const comparison=report.comparison;
  const assessment=(title:string,value:NonNullable<AgentReport['comparison']>['results'][number]['baseline'])=>`<p style="margin:12px 0 6px;font-weight:bold;">${title}</p>${value?`<p style="margin:0 0 8px;line-height:1.6;">${escape(value.decision)}</p><p style="margin:0 0 8px;line-height:1.6;">${escape(value.reason)}</p><p style="margin:0 0 14px;font-size:13px;line-height:1.6;">Trade-off: ${escape(value.tradeoff)}</p>`:'<p>Assessment pending</p>'}`;
  const comparisonHtml=comparison?section(heading('Original vs. change')+paragraphs(`Proposed change: ${comparison.change}`)+paragraphs(`${comparison.status} · ${comparison.completed} of ${comparison.total} perspectives assessed`)+comparison.results.map(result=>`<div style="margin:0 0 18px;padding:16px;border:1px solid #dedfd5;"><h3 style="margin:0 0 8px;font-size:17px;">${escape(result.name)}</h3><p style="margin:0;color:#667066;font-size:13px;">${escape(result.role)}</p>${assessment('Original',result.baseline)}${assessment('With the change',result.changed)}</div>`).join('')+paragraphs(comparison.disclaimer)):'';
  const responsesHtml=report.customerResponses?.length?section(heading('Customer responses (optional)')+paragraphs('Added by the user; not independently verified. These notes do not establish predictive accuracy.')+list(report.customerResponses.map(response=>response.text))):'';
  const comparisonText=comparison?['ORIGINAL VS. CHANGE',`Proposed change: ${comparison.change}`,`${comparison.status} · ${comparison.completed} of ${comparison.total} perspectives assessed`,...comparison.results.flatMap(result=>[`${result.name} — ${result.role}`,...(result.baseline?[`Original: ${result.baseline.decision}`,`Reason: ${result.baseline.reason}`,`Trade-off: ${result.baseline.tradeoff}`]:['Original: Assessment pending']),...(result.changed?[`With the change: ${result.changed.decision}`,`Reason: ${result.changed.reason}`,`Trade-off: ${result.changed.tradeoff}`]:['With the change: Assessment pending']),'']),comparison.disclaimer,'']:[];
  const responsesText=report.customerResponses?.length?['CUSTOMER RESPONSES (OPTIONAL)','Added by the user; not independently verified. These notes do not establish predictive accuracy.',...report.customerResponses.map(response=>`• ${response.text}`),'']:[];
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Your decision report</title><style>@media only screen and (max-width:620px){.pad{padding:24px 20px!important}.outer{padding:12px 8px!important}.title{font-size:27px!important}}</style></head><body style="margin:0;padding:0;background:#f0f0e7;color:#34433a;font-family:Arial,Helvetica,sans-serif;font-size:15px;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">Your little world, in perspective. Findings, open questions and next steps from your exploration.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f0f0e7;"><tr><td class="outer" align="center" style="padding:36px 16px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #d9decf;">
<tr><td class="pad" style="padding:28px 32px;background:#203e35;color:#f7f6e9;border-top:6px solid #c9db83;"><p style="margin:0 0 12px;font-family:monospace;font-size:18px;letter-spacing:1px;font-weight:bold;">LOG KYA BOLENGE<span style="color:#c9db83;"> ▪</span></p><p style="margin:0;color:#dae2cc;font-size:13px;">Big questions. Little people.</p></td></tr>
<tr><td class="pad" style="padding:32px;"><p style="margin:0 0 12px;font-family:monospace;font-size:11px;color:#617444;letter-spacing:2px;">YOUR DECISION REPORT</p><h1 class="title" style="margin:0 0 20px;color:#203e35;font-size:31px;line-height:1.2;">${escape(report.title)}</h1>${paragraphs(report.summary)}<p style="margin:20px 0 0;padding:12px 14px;background:#f0f4e4;color:#43573f;font-size:13px;line-height:1.6;">Keep a copy: your complete report is attached as a Markdown file.</p></td></tr>
${section(heading('What came up')+findings)}
${comparisonHtml}
${responsesHtml}
${section(heading('Still worth asking')+list(report.uncertainties))}
${section(heading('Your next steps')+list(report.nextSteps,true))}
${report.sources.length?section(heading('Sources to explore')+sources):''}
${section(`<p style="margin:0 0 20px;line-height:1.7;">Take these perspectives into your next real conversation.</p><table role="presentation" cellpadding="0" cellspacing="0"><tr><td bgcolor="#203e35" style="background:#203e35;"><a href="https://log-kya-bolenge.vercel.app" style="display:inline-block;padding:15px 22px;color:#ffffff;text-decoration:none;font-weight:bold;font-size:14px;">Open Log kya bolenge &rarr;</a></td></tr></table><p style="margin:16px 0 0;color:#697369;font-size:12px;line-height:1.6;">The full report is in this email and its attachment. The button opens the app.</p>`)}
<tr><td class="pad" style="padding:24px 32px;background:#f7f7ef;border-top:1px solid #e5e5da;"><p style="margin:0 0 10px;color:#596353;font-size:12px;line-height:1.7;">${escape(report.disclaimer)}</p><p style="margin:0;color:#72796c;font-size:11px;line-height:1.6;">Sent because you requested a decision report from Log kya bolenge.</p></td></tr>
</table></td></tr></table></body></html>`;
  const text=['LOG KYA BOLENGE','Big questions. Little people.','',report.title,'',report.summary,'','WHAT CAME UP','',...report.findings.flatMap((f,i)=>[`${i+1}. ${f.title}`,status(f),f.detail,...(f.verification?[f.verification.reason]:[]),...quotes(f).map(item=>`“${item.quote}” — ${report.sources.find(source=>source.id===item.sourceId)!.title}`),`Sources: ${referencedSources(f).map(source=>`${source.title}${safeUrl(source.url)?`: ${source.url}`:''}`).join(', ')||'None'}`,`Conversations: ${conversations(f).join(', ')||'None'}`,...(comparisonNames(f).length?[`Comparison perspectives: ${comparisonNames(f).join(', ')}`]:[]),'']),...comparisonText,...responsesText,'STILL WORTH ASKING',...report.uncertainties.map(t=>`• ${t}`),'','YOUR NEXT STEPS',...report.nextSteps.map((t,i)=>`${i+1}. ${t}`),'','SOURCES',...report.sources.map(s=>`${s.title}${safeUrl(s.url)?`: ${s.url}`:''}`),'','Your complete report is attached as a Markdown file.','Open the app: https://log-kya-bolenge.vercel.app','',report.disclaimer].join('\n');
  return {html,text};
}
